= Gründe für die Ablehnung von KI-Detektoren

== Funktionsweise von KI-Detektoren

Um die Problematik von KI-Detektoren genauer beleuchten zu können, muss zu Beginn die Funktionsweise dieser erläutert werden. Im Gegensatz zu menschlichen Lesern analysieren KI-Detektoren Texte nicht auf den inhaltlichen Sinn, sondern auf statistische Muster. Dabei stützen sich Detektoren auf Metriken wie die Perplexität, d.\u{2009}h. die Vorhersagbarkeit der Wortwahl, und die Burstiness, d.\u{2009}h. die Varianz der Satzlänge und -komplexität @gehrmann2019. Da große Sprachmodelle (engl. Large Language Models, LLMs) den statistisch wahrscheinlichsten nächsten Baustein, ein sog. Token, vorhersagen, produzieren LLMs Texte mit geringer Perplexität und Burstiness. Ein KI-Detektor klassifiziert dementsprechend Texte mit großer Vorhersagbarkeit der Wortwahl, d.\u{2009}h. niedriger Perplexität, und niedriger Burstiness, d.\u{2009}h. Sätze in gleichmäßiger Länge und identischer Struktur, als KI-generiert.

== Geringe Genauigkeit und Fehlklassifikationen

Diese statistische Klassifikation ist fehleranfällig, da sie ausschließlich auf Wahrscheinlichkeiten beruht. Wird ein von Menschen verfasster Text als KI-generiert eingestuft, spricht man von einem sog. False Positive.

Ein bekanntes Beispiel ist die Einordnung der Verfassung der Vereinigten Staaten von Amerika als KI-generiert. Dabei wirken zwei Effekte zusammen: Zum einen handelt es sich um ein juristisches Dokument mit präzisen, formelhaften Formulierungen und geringer sprachlicher Varianz. Zum anderen ist der Text nach Angaben des GPTZero-Entwicklers Edward Tian in den Trainingsdaten vieler Sprachmodelle stark überrepräsentiert, sodass diese Modelle darauf trainiert sind, ähnliche Texte zu erzeugen @edwards2023. Der Detektor erkennt in diesem Fall also gewissermaßen sein eigenes Vorbild wieder.

Dass es sich nicht um Einzelfälle handelt, zeigen systematische Untersuchungen. Eine internationale Studie, die verbreitete Detektionswerkzeuge unter kontrollierten Bedingungen getestet hat, kam zu dem Ergebnis, dass keines von ihnen zuverlässig zwischen menschlichen und KI-generierten Texten unterscheidet @weberwulff2023. Selbst große Anbieter empfehlen ihre eigenen Klassifikatoren nicht mehr: OpenAI stellte den eigenen Detektor am 20. Juli 2023 wegen zu geringer Trefferquote ein. Bereits in der herstellereigenen Evaluation bei Veröffentlichung des Werkzeugs wurden nur rund ein Viertel der KI-Texte korrekt erkannt, während fast jeder zehnte menschliche Text fälschlich als KI eingestuft wurde @openai2023.

Hinzu kommt ein verbreiteter Denkfehler im Umgang mit Fehlerquoten. Aus einer angegebenen Falsch-Positiv-Rate von einem Prozent folgt gerade nicht, dass ein markierter Text mit 99-prozentiger Wahrscheinlichkeit KI-generiert ist. Diese Wahrscheinlichkeit hängt zusätzlich von der Basisrate ab, also vom tatsächlichen Anteil KI-generierter Arbeiten im geprüften Jahrgang — und dieser Anteil ist in der Praxis grundsätzlich unbekannt @bassett2026. Ein Detektionswert lässt sich damit nicht sinnvoll in eine Aussage über den Einzelfall übersetzen.

Solche Fehlklassifikationen erzeugen zudem einen „Chilling Effect“: Schreibende geraten unter Generalverdacht und richten ihr Schreiben defensiv an vermeintlich unverdächtigen Formulierungen aus, was Leistungsbereitschaft und gestalterische Freiheit beeinträchtigt @giray2025.

== Umgehbarkeit von KI-Detektoren

KI-Detektoren lassen sich mit geringem Aufwand umgehen. Bereits leichte Überarbeitungen, Paraphrasierungen oder der Umweg über eine maschinelle Übersetzung senken die Erkennungsrate deutlich @weberwulff2023. Es existieren Werkzeuge, die genau darauf ausgelegt sind @perkins2024.

Daraus folgt ein Einwand, der die Abschreckungswirkung von Detektoren grundsätzlich in Frage stellt: Wer die Umgehung beherrscht, wird nicht erfasst. Detektoren messen deshalb weniger die unzulässige Nutzung generativer KI als vielmehr die fehlende Routine im Umgang mit ihr sowie den fehlenden Zugang zu leistungsfähigeren Werkzeugen @bassett2026. Sie belasten damit systematisch die weniger versierten Studierenden, während sie gerade diejenigen nicht erreichen, auf die sie zielen.

== Bias gegenüber Nicht-Muttersprachlern

Bei der Klassifikation von Texten von Nicht-Muttersprachlern kommt es zu systematischen Verzerrungen, sog. Bias. Eine Studie der Universität Stanford aus dem Jahr 2023 prüfte sieben verbreitete Detektoren an 91 TOEFL-Essays. Die Detektoren stuften im Durchschnitt über 61\u{2009}% dieser Essays fälschlich als KI-generiert ein, während Texte muttersprachlicher Verfasser nahezu fehlerfrei erkannt wurden @liang2023.

Erklären lässt sich der Befund mit der Funktionsweise der Detektoren: Wer in einer Fremdsprache formuliert, verwendet tendenziell kürzere Sätze, einen kleineren Wortschatz und weniger komplexe Konstruktionen. Perplexität und Burstiness sinken — und genau das werten Detektoren als Hinweis auf KI.

Die Anbieter haben auf die Studie reagiert. GPTZero veröffentlichte 2023 ein überarbeitetes Modell und bezeichnete den Befund als überholt. Eine unabhängige Nachmessung an demselben Datensatz ergab für dieses überarbeitete Modell jedoch weiterhin eine Falsch-Positiv-Rate von 7,7\u{2009}% @emi2024. Auch nach der Nachbesserung wird also etwa jeder dreizehnte Text zu Unrecht markiert. Für internationale duale Studierende sowie duale Studierende mit Migrationshintergrund wiegt das besonders schwer: Eine Fehlerquote, die sich nicht zufällig, sondern entlang der sprachlichen Herkunft verteilt, verstärkt bestehende Ungleichheiten und erzeugt reale Benachteiligungen.

== Rechtliche Einordnung

Der Einsatz externer Detektionsdienste ist datenschutzrechtlich fragwürdig. Vor der Einführung von KI-Anwendungen, die personenbezogene oder studienrelevante Daten verarbeiten, sind klare Rechtsgrundlagen, definierte Verantwortlichkeiten und eine Datenschutz-Folgenabschätzung nach DSGVO Art.\u{00A0}35 erforderlich. Viele Dienste verarbeiten Texte in Rechenzentren außerhalb der EU, teils ohne transparenten Umgang mit Speicherung und Weiterverwendung. Damit setzen Hochschulen die Daten ihrer Studierenden und sich selbst rechtlichen Risiken aus. Hinzu kommt im Kontext der DHBW, dass Studienarbeiten häufig mit Sperrvermerken versehen sind, da unternehmensintern Daten verwendet werden. Ein Verstoß gegen einen solchen Sperrvermerk durch den Upload in einen externen Dienst setzt die DHBW einem rechtlichen Risiko und möglichen Klagen der dualen Partner aus.

Ebenfalls anzumerken ist, dass im deutschen Prüfungsrecht die Hochschule die Beweislast trägt. Bei einem Täuschungsvorwurf muss sie die Täuschung nachweisen. Da Detektionssoftware ausschließlich Wahrscheinlichkeiten liefert und keine Beweise im juristischen Sinn, ist sie als Grundlage für disziplinarische Maßnahmen nicht tragfähig. Ein Sanktionsverfahren auf einem Detektionswert aufzubauen, wäre rechtlich fragwürdig, angreifbar und gegenüber den Betroffenen unfair, denn ein Detektionswert ist kein Beweismittel und darf auch nicht als „unterstützendes“ Indiz in ein Täuschungsverfahren einfließen. Wer einem unzuverlässigen Wahrscheinlichkeitswert über den Umweg der freien Beweiswürdigung doch Gewicht verleiht, verlagert die Beweislast faktisch auf die Studierenden und unterläuft den Grundsatz fairer Prüfungen. Der AStA lehnt eine solche Verwendung ausdrücklich ab.

== Position des AStA

Wir benennen den Effekt bewusst zweiseitig, denn eine glaubwürdige Integritätssicherung wirkt abschreckend auf Täuschungsversuche und ist ein legitimes Ziel. Der entscheidende Unterschied ist, dass diese Abschreckung nicht auf der Bestrafung Unschuldiger beruhen darf. Genau das aber riskiert ein Verfahren, das Fehlalarme zur Sanktionsgrundlage macht. Die Schwächen der KI-Detektion sind technischer, rechtlicher, ethischer und pädagogischer Natur. In ihrer Summe lassen sie sich nicht beheben, ohne das Verfahren selbst aufzugeben. Der AStA zieht daraus eine klare Konsequenz: KI-Detektoren gehören nicht in den Prüfungskontext. Das bedeutet nicht die Abschaffung schriftlicher Arbeiten, sondern den Verzicht auf eine untaugliche Überwachungstechnologie zugunsten einer unmittelbaren fachlichen Überprüfung der eingereichten Leistung.

Der naheliegende Vergleich mit Plagiatssoftware trägt die Detektoren gerade nicht, denn ein Plagiatsbefund verweist auf eine konkrete, überprüfbare Quelle, die ein Mensch nachlesen und bestätigen kann. Ein KI-Detektor liefert dagegen nur eine Wahrscheinlichkeit ohne nachprüfbaren Beleg. Es gibt nichts, was sich gegenprüfen ließe. Was bei Plagiaten ein überprüfbarer Hinweis ist, bleibt bei KI-Detektoren eine bloße Behauptung. Der Vergleich rechtfertigt deshalb keinen Einsatz, sondern unterstreicht die Ablehnung.